version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django: &django # 引用
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: ccdj_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ccdj_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:3.2

  celeryworker:
    <<: *django
    image: ccdj_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ccdj_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: ccdj_production_flower
    ports:
      - "5555:5555"
    command: /start-flower
